# Prevents locally installed Bower dependencies
# from being copied into the Docker image
#skip_files:
#  - ^(.*/)?.*/bower_components/.*$

runtime: nodejs
env: flex

env_variables:
  DBUSER: test
  DBPWD: test
  DBSCHEMA: product_management_local
  DBHOST: /cloudsql/alife-inclusive:asia-northeast1:alife-inclusive
  NODE_ENV: production

beta_settings:
  # The connection name of your instance, available by using
  # 'gcloud beta sql instances describe [INSTANCE_NAME]' or from
  # the Instance details page in the Google Cloud Platform Console.
  cloud_sql_instances: alife-inclusive:asia-northeast1:alife-inclusive